const OK = 200;
const ACCEPTED = 202;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  INTERNAL_SERVER_ERROR,
  OK,
  BAD_REQUEST,
  NOT_FOUND,
  UNAUTHORIZED,
  ACCEPTED

};
